apiVersion: v1
kind: Service
metadata:
  name: scalar-svc
  labels:
    app: scalar
  namespace: scalar-test
spec:
  selector:
   app: scalar
  sessionAffinity: ClientIP
  externalIPs:
   - 168.246.41.185
  ports:
   - nodePort: 31607
     port: 81
     protocol: TCP
     targetPort: 5700
  type: LoadBalancer
status:
 loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: image-svc
  labels:
    app: image
  namespace: image-test
spec:
  selector:
   app: image
  sessionAffinity: ClientIP
  externalIPs:
   - 168.246.41.185
  ports:
   - nodePort: 31609
     port: 82
     protocol: TCP
     targetPort: 5700
  type: LoadBalancer
status:
 loadBalancer: {}
