apiVersion: v1
kind: Service
metadata:
  name: scalar-svc
spec:
  selector:
   app: scalar
  sessionAffinity: ClientIP
  externalIPs:
   - 168.246.41.45
  ports:
   - nodePort: 31101
     port: 81
     protocol: TCP
     targetPort: 5700
  type: LoadBalancer
status:
 loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: image-svc
spec:
  selector:
   app: image
  sessionAffinity: ClientIP
  externalIPs:
   - 168.246.41.45
  ports:
   - nodePort: 31102
     port: 82
     protocol: TCP
     targetPort: 5700
  type: LoadBalancer
status:
 loadBalancer: {}
