apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcvserver-deploy
  labels:
    apps: rcvserver-app
spec:
  replicas: 1
  selector:
   matchLabels:
    app: rcvserver
  template:
    metadata:
     labels:
       app: rcvserver
    spec:
      containers:
      - name: rcvserver
        image: wnghks3030/rcvserver:final
        args: ["-p","5600"]
        ports:
        - containerPort: 5600

---
apiVersion: v1
kind: Service
metadata:
 name: rcv-svc
 labels:
  apps: rcvserver-svc
spec: 
 clusterIP: 10.110.196.1
 externalIPs: 
  - 168.246.41.45
 externalTrafficPolicy: Cluster
 ports:
  - nodePort: 31100
    port: 80
    protocol: TCP
    targetPort: 5600
 selector:
  app: rcvserver
 sessionAffinity: ClientIP
 type: LoadBalancer
status:
 loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
 name: scalar-svc
 namespace: scalar-test
 labels:
  apps: scalar
spec:
 clusterIP: 10.110.196.2
 externalIPs:
 - 168.246.41.45
 externalTrafficPolicy: Cluster
 ports:
  - nodePort: 31101
    port: 80
    targetPort: 5700
 selector:
  app: scalar
 sessionAffinity: ClientIP
 type: LoadBalancer
status:
 loadBalancer: {}
